export const PROGRAMS = [
  { id: "sirius", name: "Sirius" },
  { id: "polaris", name: "Polaris" },
];

export const ROLES = [
  { id: "frontend", name: "Front-end" },
  { id: "backend", name: "Back-end" },
  { id: "qa", name: "QA" },
  { id: "pm", name: "Program Manager" },
];

export const DEFAULT_CATEGORIES_FE_BE = [
  {
    id: "generic",
    name: "Generic",
    skills: [
      { name: "Motivation", level: 0 },
      { name: "Potential", level: 0 },
      { name: "Communication", level: 0 },
      { name: "Confidence", level: 0 },
      { name: "English", level: 0 },
      { name: "Lecturing", level: 0 },
      { name: "Presentations", level: 0 },
      { name: "Leadership", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "javascript",
    name: "Javascript",
    skills: [
      { name: "Javascript", level: 0 },
      { name: "Nodejs", level: 0 },
      { name: "async/Promises", level: 0 },
      { name: "parallel", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "data-stores",
    name: "Data stores",
    skills: [
      { name: "mysql", level: 0 },
      { name: "mongodb", level: 0 },
      { name: "dynamo", level: 0 },
      { name: "MSSQL", level: 0 },
      { name: "NeDB", level: 0 },
      { name: "S3", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "build-tools",
    name: "Build tools",
    skills: [
      { name: "BLT", level: 0 },
      { name: "docksal", level: 0 },
      { name: "Lando", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "drupal",
    name: "Drupal",
    skills: [
      { name: "Drupal", level: 0 },
      { name: "Migrate", level: 0 },
      { name: "Multisite", level: 0 },
      { name: "Domain", level: 0 },
      { name: "Headless", level: 0 },
      { name: "Static", level: 0 },
      { name: "Commerce", level: 0 },
      { name: "Twig", level: 0 },
      { name: "Tests", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "ci-cd",
    name: "CI/CD",
    skills: [
      { name: "Gitlab pipelines", level: 0 },
      { name: "Jenkins", level: 0 },
      { name: "Ansible", level: 0 },
      { name: "Others", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "cmd",
    name: "CMD",
    skills: [
      { name: "Vim, nano", level: 0 },
      { name: "find, grep", level: 0 },
      { name: "awk, sed", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "vcs",
    name: "VCS",
    skills: [{ name: "GIT", level: 0 }],
    averageLevel: 0,
  },
  {
    id: "scripting",
    name: "Scripting",
    skills: [
      { name: "Bash", level: 0 },
      { name: "Python", level: 0 },
      { name: "Expect", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "devops",
    name: "Devops",
    skills: [
      { name: "Devops", level: 0 },
      { name: "AWS", level: 0 },
      { name: "GCP", level: 0 },
      { name: "Azure", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "fe-frameworks",
    name: "FE frameworks",
    skills: [
      { name: "React", level: 0 },
      { name: "Vue", level: 0 },
      { name: "Angular", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "mobile",
    name: "Mobile",
    skills: [
      { name: "Mobile", level: 0 },
      { name: "Hybrid", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "seo",
    name: "SEO",
    skills: [
      { name: "SEO", level: 0 },
      { name: "GTM", level: 0 },
      { name: "Matomo", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "search",
    name: "Search",
    skills: [
      { name: "Solr", level: 0 },
      { name: "Elasticsearch", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "cache",
    name: "Cache",
    skills: [
      { name: "Varnish", level: 0 },
      { name: "Redis", level: 0 },
      { name: "Memcache", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "hosting",
    name: "Hosting",
    skills: [
      { name: "Platform.sh", level: 0 },
      { name: "Acquia", level: 0 },
      { name: "Pantheon", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "virtualization",
    name: "Virtualization",
    skills: [
      { name: "Docker", level: 0 },
      { name: "docker-compose", level: 0 },
      { name: "Kubernetes", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "sysadmin",
    name: "Sysadmin",
    skills: [
      { name: "Linux admin", level: 0 },
      { name: "Networking", level: 0 },
      { name: "Security", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "misc-languages",
    name: "Misc languages",
    skills: [
      { name: "Regex", level: 0 },
      { name: "Xpath/XSL", level: 0 },
    ],
    averageLevel: 0,
  },
];

export const DEFAULT_CATEGORIES_QA = [
  {
    id: "generic",
    name: "Generic",
    skills: [
      { name: "Motivation", level: 0 },
      { name: "Potential", level: 0 },
      { name: "Communication", level: 0 },
      { name: "Confidence", level: 0 },
      { name: "English", level: 0 },
      { name: "Lecturing", level: 0 },
      { name: "Presentations", level: 0 },
      { name: "Leadership", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "languages",
    name: "Languages",
    skills: [
      { name: "SQL", level: 0 },
      { name: "PHP", level: 0 },
      { name: "JS", level: 0 },
      { name: "CSS", level: 0 },
      { name: "Bash scripts", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "data-stores",
    name: "Data stores",
    skills: [
      { name: "Drupal", level: 0 },
      { name: "Migrate", level: 0 },
      { name: "Multisite", level: 0 },
      { name: "Static", level: 0 },
      { name: "Commerce", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "cmd",
    name: "CMD",
    skills: [{ name: "UNIX CMD", level: 0 }],
    averageLevel: 0,
  },
  {
    id: "vcs",
    name: "VCS",
    skills: [{ name: "GIT", level: 0 }],
    averageLevel: 0,
  },
  {
    id: "devops",
    name: "Devops",
    skills: [{ name: "Devops", level: 0 }],
    averageLevel: 0,
  },
  {
    id: "seo",
    name: "SEO",
    skills: [{ name: "SEO", level: 0 }],
    averageLevel: 0,
  },
  {
    id: "virtualization",
    name: "Virtualization",
    skills: [{ name: "Docker", level: 0 }],
    averageLevel: 0,
  },
  {
    id: "drupal",
    name: "Drupal",
    skills: [
      { name: "Drupal", level: 0 },
      { name: "Migrate", level: 0 },
      { name: "Multisite", level: 0 },
      { name: "Domain", level: 0 },
      { name: "Headless", level: 0 },
      { name: "Static", level: 0 },
      { name: "Commerce", level: 0 },
      { name: "Twig", level: 0 },
      { name: "Tests", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "ci-cd",
    name: "CI/CD",
    skills: [
      { name: "Gitlab pipelines", level: 0 },
      { name: "Jenkins", level: 0 },
      { name: "Ansible", level: 0 },
      { name: "Others", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "cmd",
    name: "CMD",
    skills: [
      { name: "Vim, nano", level: 0 },
      { name: "find, grep", level: 0 },
      { name: "awk, sed", level: 0 },
    ],
    averageLevel: 0,
  },

  {
    id: "scripting",
    name: "Scripting",
    skills: [
      { name: "Bash", level: 0 },
      { name: "Python", level: 0 },
      { name: "Expect", level: 0 },
    ],
    averageLevel: 0,
  },

  {
    id: "fe-frameworks",
    name: "FE frameworks",
    skills: [
      { name: "React", level: 0 },
      { name: "Vue", level: 0 },
      { name: "Angular", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "mobile",
    name: "Mobile",
    skills: [
      { name: "Mobile", level: 0 },
      { name: "Hybrid", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "seo",
    name: "SEO",
    skills: [
      { name: "SEO", level: 0 },
      { name: "GTM", level: 0 },
      { name: "Matomo", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "misc-languages",
    name: "Misc languages",
    skills: [
      { name: "Regex", level: 0 },
      { name: "Xpath/XSL", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "qa-specific",
    name: "QA Specific",
    skills: [
      { name: "Regex", level: 0 },
      { name: "Xpath/XSL", level: 0 },
      { name: "Behat", level: 0 },
      { name: "Appium", level: 0 },
      { name: "Protractor", level: 0 },
      { name: "Katalon", level: 0 },
      { name: "Jest", level: 0 },
      { name: "PHPUnit", level: 0 },
      { name: "Cucumber", level: 0 },
      { name: "Puppeteer", level: 0 },
      { name: "OWASP ZAP", level: 0 },
      { name: "Detectify", level: 0 },
      { name: "Browser DevTools", level: 0 },
      { name: "Trakr", level: 0 },
      { name: "Browserstack", level: 0 },
      { name: "Test Cases", level: 0 },
      { name: "Review of complex architectures", level: 0 },
      { name: "JMeter", level: 0 },
      { name: "API", level: 0 },
      { name: "Complex tasks", level: 0 },
      { name: "Accessibility", level: 0 },
      { name: "Penetration", level: 0 },
      { name: "OWASP ZAP", level: 0 },
      { name: "Detectify", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "scrum",
    name: "Scrum",
    skills: [
      { name: "Client management", level: 0 },
      { name: "Business analyst", level: 0 },
      { name: "Onboarding speed", level: 0 },
      { name: "Sprint Demos", level: 0 },
      { name: "Documentation", level: 0 },
      { name: "Client trainings", level: 0 },
      { name: "Discovery", level: 0 },
      { name: "UAT support", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "methodologies",
    name: "Methodologies",
    skills: [
      { name: "BDD", level: 0 },
      { name: "TDD", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "misc-files",
    name: "Misc files",
    skills: [
      { name: "JSON", level: 0 },
      { name: "yaml", level: 0 },
    ],
    averageLevel: 0,
  },
];

export const DEFAULT_CATEGORIES_PM = [
  {
    id: "generic",
    name: "Generic",
    skills: [
      { name: "Motivation", level: 0 },
      { name: "Potential", level: 0 },
      { name: "Communication", level: 0 },
      { name: "Confidence", level: 0 },
      { name: "English", level: 0 },
      { name: "Lecturing", level: 0 },
      { name: "Presentations", level: 0 },
      { name: "Leadership", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "pm-methodologies",
    name: "PM Methodologies",
    skills: [
      { name: "Process", level: 0 },
      { name: "Integration", level: 0 },
      { name: "Scope", level: 0 },
      { name: "Time", level: 0 },
      { name: "Cost", level: 0 },
      { name: "Quality", level: 0 },
      { name: "Human Resource", level: 0 },
      { name: "Communications", level: 0 },
      { name: "Procurement", level: 0 },
      { name: "Stakeholder", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "pm-specific",
    name: "PM Specific",
    skills: [
      { name: "Critical Thinking", level: 0 },
      { name: "Data Analysis", level: 0 },
      { name: "Research", level: 0 },
      { name: "Problem Solving", level: 0 },
      { name: "Organizational", level: 0 },
      { name: "Documentation", level: 0 },
      { name: "Communication", level: 0 },
      { name: "Negotiation", level: 0 },
      { name: "Leadership", level: 0 },
      { name: "Multitasking", level: 0 },
      { name: "Industry Expertise", level: 0 },
      { name: "Team Building", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "Tools",
    name: "tools",
    skills: [
      { name: "Metric", level: 0 },
      { name: "Float", level: 0 },
      { name: "Jira", level: 0 },
      { name: "Confluence", level: 0 },
      { name: "Google/MS Office", level: 0 },
    ],
    averageLevel: 0,
  },
  {
    id: "Technologies",
    name: "technologies",
    skills: [
      { name: "Internet", level: 0 },
      { name: "Drupal", level: 0 },
      { name: "AWS", level: 0 },
      { name: "Commerce", level: 0 },
      { name: "UX/UI Concept", level: 0 },
      { name: "Accessibility", level: 0 },
      { name: "Development", level: 0 },
      { name: "CI/CD", level: 0 },
      { name: "Security", level: 0 },
      { name: "SEO", level: 0 },
    ],
    averageLevel: 0,
  },
];
